//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeData.ModelDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingServerOnline
    {
        public int ID { get; set; }
        public string ServerName { get; set; }
        public byte[] Img { get; set; }
        public string Tell { get; set; }
        public string Address { get; set; }
        public string Motto { get; set; }
        public Nullable<bool> Enable { get; set; }
    }
}
